### PR TITLE
Only look for status.phase=running pods by label

### PR DESCRIPTION
**Pull request by hiddeco**
Given a pod needs to be running to be able to port forward, and to
work around scenarios where a node failure occured and one pod hangs
in a 'terminating' state, only look for running pods to increase the
chance to find one healthy match.

I was unable to mock this scenario in to tests due to https://github.com/kubernetes/client-go/issues/326

### CODE REVIEW

**Comment by justinbarrick** [comment]
Welcome @hiddeco! It looks like this is your first PR to justinbarrick/go-k8s-portforward 🎉

**Comment by justinbarrick** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/justinbarrick/go-k8s-portforward/pull/7#" title="Author self-approved">hiddeco</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approvers: 

If they are not already assigned, you can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=justinbarrick%2Fgo-k8s-portforward).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/justinbarrick/go-k8s-portforward/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by hiddeco** [comment]
Thanks @justinbarrick :tulip:

**Pull request merged**
